Fixing cookstyle PR check introduced in PR#622
3s
Run bundle exec cookstyle --chefstyle
Inspecting 21 files
...................C.

Offenses:

Error: lib/kitchen/driver/ec2.rb:589:56: C: [Correctable] Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping. (https://rubystyle.guide#consistent-string-literals)
              output = server.console_output.output || ''
                                                       ^^

21 files inspected, 1 offense detected, 1 offense autocorrectable
Error: Process completed with exit code 1.

https://github.com/test-kitchen/kitchen-ec2/pull/622/files

Signed-off-by: mayankgupta57 <mayank.g57@gmail.com>